CXX = gcc

BUILD = diazh.buildrooms.c

ADVENTURE = diazh.adventure.c

main:
	${CXX} -o diazh.adventure ${ADVENTURE} -lpthread

build:
	${CXX} -o diazh.buildrooms ${BUILD} 

cleanA:
	rm -f diazh.adventure

cleanB:
	rm -f diazh.buildrooms