CXX = gcc

BUILD = diazh.buildrooms.c

ADVENTURE = diazh.adventure.c

main:
	${CXX} ${ADVENTURE} -o diazh.adventure

build:
	${CXX} ${BUILD} -o diazh.buildrooms

cleanA:
	rm -f diazh.adventure

cleanB:
	rm -f diazh.buildrooms