CXX = gcc

BUILD = diazh.build.c

ADVENTURE = diazh.adventure.c

main:
	${CXX} ${ADVENTURE} -o diazh.adventure

build:
	${CXX} ${BUILD} -o diazh.build

cleanA:
	rm -f diazh.adventure

cleanB:
	rm -f diazh.build